export class StockMap {
  map = {
    "ACC": "ACC Limited",
    "ADANIPORTS": "Adani Ports & SEZ Limited",
    "AMBUJACEM": "Ambuja Cements Ltd.",
    "ASIANPAINT": "Asian Paints Ltd.",
    "AUROPHARMA": "Aurobindo Pharma Ltd.",
    "AXISBANK": "Axis Bank Ltd.",
    "BAJAJ-AUTO": "Bajaj Auto Ltd.",
    "BANKBARODA": "Bank of Baroda",
    "BHARTIARTL": "Bharti Airtel Ltd.",
    "BOSCHLTD": "Bosch Ltd.",
    "BPCL": "Bharat Petroleum Corporation",
    "CIPLA": "Cipla Ltd.",
    "COALINDIA": "Coal India Ltd.",
    "DRREDDY": "Dr. Reddy's Laboratories Ltd.",
    "EICHERMOT": "Eicher Motors",
    "GAIL": "GAIL (India) Ltd.",
    "HCLTECH": "HCL Technologies Ltd.",
    "HDFC": "Housing Development Finance Corporation Ltd.",
    "HDFCBANK": "HDFC Bank Ltd.",
    "HEROMOTOCO": "Hero MotoCorp Ltd.",
    "HINDALCO": "Hindalco Industries Ltd.",
    "HINDUNILVR": "Hindustan Unilever Ltd.",
    "IBULHSGFIN": "Indiabulls Housing Finance Ltd.",
    "ICICIBANK": "ICICI Bank Ltd.",
    "INDUSINDBK": "IndusInd Bank Ltd.",
    "INFRATEL": "Bharti Infratel",
    "INFY": "Infosys Ltd.",
    "IOC": "Indian Oil Corporation",
    "ITC": "ITC Limited",
    "KOTAKBANK": "Kotak Mahindra Bank Ltd.",
    "LT": "Larsen & Toubro Ltd.",
    "LUPIN": "Lupin Limited",
    "MARUTI": "Maruti Suzuki India Ltd.",
    "NIFTY 50": "NIFTY 50",
    "NTPC": "NTPC Limited",
    "ONGC": "Oil & Natural Gas Corporation Ltd.",
    "POWERGRID": "PowerGrid Corporation of India Ltd.",
    "RELIANCE": "Reliance Industries Ltd.",
    "SBIN": "State Bank of India",
    "SUNPHARMA": "Sun Pharmaceutical Industries Ltd.",
    "TATAMOTORS": "Tata Motors Ltd.",
    "TATAMTRDVR": "Tata Motors (DVR",
    "TATAPOWER": "Tata Power Co. Ltd.",
    "TATASTEEL": "Tata Steel Ltd.",
    "TCS": "Tata Consultancy Services Ltd.",
    "TECHM": "Tech Mahindra Ltd.",
    "ULTRACEMCO": "UltraTech Cement Ltd.",
    "VEDL": "Vedanta Ltd.",
    "WIPRO": "Wipro",
    "YESBANK": "Yes Bank Ltd.",
    "ZEEL": "Zee Entertainment Enterprises Ltd."
  };
}
